src/MetaNotes/Controllers/HeaderController.cs
using MetaNotes.Common;
using MetaNotes.ModelBuilders;
using System.Web.Mvc;

namespace MetaNotes.Controllers
{
    public class HeaderController : BaseController
    {
        public PartialViewResult Menu()
        {
            var builder = new HeaderMenuModelBuiler();
            var model = builder.Build(GetUserId(), UserIsInRole(RolesConstants.AdminRole));
            return PartialView("~/Views/Header/HeaderPartial.cshtml", model);
        }
	}
}

src/MetaNotes/Views/Shared/Layouts/MainLayout.cshtml
@using MetaNotes.Internationalization.UI.Layout
@{
    Layout = "~/Views/Shared/Layouts/_Layout.cshtml";
}

<header class="navbar navbar-static-top navbar-inverse bs-docs-nav pull-center" id="top" role="banner">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        </button>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <div class="row">
            <div class=".col-xs-offset-1 col-xs-10 col-xs-offset-1">
                @{ Html.RenderAction("Menu", "Header"); }
            </div>
        </div>
    </nav>
</header>

@RenderBody()

src/MetaNotes/Views/Shared/Layouts/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title (Тестовое задание Алексея Поликарпова)</title>
    @Styles.Render("~/bundles/styles/main")
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="container">
        @RenderBody()

        <footer>
            @Scripts.Render("~/bundles/scripts/main")
            @RenderSection("Scripts", required: false)
        </footer>
    </div>
</body>
</html>